/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompeteRouteImport } from './routes/compete'
import { Route as FiltersRouteImport } from './routes/filters'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ArcadeBoardRouteImport } from './routes/arcade_.board'
import { Route as ArcadeConnectFourRouteImport } from './routes/arcade_.connect-four'
import { Route as ArcadeMastermindRouteImport } from './routes/arcade_.mastermind'
import { Route as ArcadeQuizRaceRouteImport } from './routes/arcade_.quiz-race'
import { Route as ArcadeRoomsRouteImport } from './routes/arcade_.rooms'
import { Route as ClueSportRouteImport } from './routes/clue.$sport'
import { Route as EndlessSportRouteImport } from './routes/endless.$sport'
import { Route as ModesSportRouteImport } from './routes/modes.$sport'
import { Route as PlaySportRouteImport } from './routes/play.$sport'
import { Route as ArcadeRoomsIdRouteImport } from './routes/arcade_.rooms_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeteRoute = CompeteRouteImport.update({
  id: '/compete',
  path: '/compete',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltersRoute = FiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArcadeBoardRoute = ArcadeBoardRouteImport.update({
  id: '/arcade_/board',
  path: '/arcade/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeConnectFourRoute = ArcadeConnectFourRouteImport.update({
  id: '/arcade_/connect-four',
  path: '/arcade/connect-four',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeMastermindRoute = ArcadeMastermindRouteImport.update({
  id: '/arcade_/mastermind',
  path: '/arcade/mastermind',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeQuizRaceRoute = ArcadeQuizRaceRouteImport.update({
  id: '/arcade_/quiz-race',
  path: '/arcade/quiz-race',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoomsRoute = ArcadeRoomsRouteImport.update({
  id: '/arcade_/rooms',
  path: '/arcade/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ClueSportRoute = ClueSportRouteImport.update({
  id: '/clue/$sport',
  path: '/clue/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const EndlessSportRoute = EndlessSportRouteImport.update({
  id: '/endless/$sport',
  path: '/endless/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesSportRoute = ModesSportRouteImport.update({
  id: '/modes/$sport',
  path: '/modes/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySportRoute = PlaySportRouteImport.update({
  id: '/play/$sport',
  path: '/play/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoomsIdRoute = ArcadeRoomsIdRouteImport.update({
  id: '/arcade_/rooms_/$id',
  path: '/arcade/rooms/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/auth': typeof AuthRoute
  '/compete': typeof CompeteRoute
  '/filters': typeof FiltersRoute
  '/leaderboard': typeof LeaderboardRoute
  '/upgrade': typeof UpgradeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/arcade/board': typeof ArcadeBoardRoute
  '/arcade/connect-four': typeof ArcadeConnectFourRoute
  '/arcade/mastermind': typeof ArcadeMastermindRoute
  '/arcade/quiz-race': typeof ArcadeQuizRaceRoute
  '/arcade/rooms': typeof ArcadeRoomsRoute
  '/clue/$sport': typeof ClueSportRoute
  '/endless/$sport': typeof EndlessSportRoute
  '/modes/$sport': typeof ModesSportRoute
  '/play/$sport': typeof PlaySportRoute
  '/arcade/rooms/$id': typeof ArcadeRoomsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/auth': typeof AuthRoute
  '/compete': typeof CompeteRoute
  '/filters': typeof FiltersRoute
  '/leaderboard': typeof LeaderboardRoute
  '/upgrade': typeof UpgradeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/arcade/board': typeof ArcadeBoardRoute
  '/arcade/connect-four': typeof ArcadeConnectFourRoute
  '/arcade/mastermind': typeof ArcadeMastermindRoute
  '/arcade/quiz-race': typeof ArcadeQuizRaceRoute
  '/arcade/rooms': typeof ArcadeRoomsRoute
  '/clue/$sport': typeof ClueSportRoute
  '/endless/$sport': typeof EndlessSportRoute
  '/modes/$sport': typeof ModesSportRoute
  '/play/$sport': typeof PlaySportRoute
  '/arcade/rooms/$id': typeof ArcadeRoomsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/arcade': typeof ArcadeRoute
  '/auth': typeof AuthRoute
  '/compete': typeof CompeteRoute
  '/filters': typeof FiltersRoute
  '/leaderboard': typeof LeaderboardRoute
  '/upgrade': typeof UpgradeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/arcade_/board': typeof ArcadeBoardRoute
  '/arcade_/connect-four': typeof ArcadeConnectFourRoute
  '/arcade_/mastermind': typeof ArcadeMastermindRoute
  '/arcade_/quiz-race': typeof ArcadeQuizRaceRoute
  '/arcade_/rooms': typeof ArcadeRoomsRoute
  '/clue/$sport': typeof ClueSportRoute
  '/endless/$sport': typeof EndlessSportRoute
  '/modes/$sport': typeof ModesSportRoute
  '/play/$sport': typeof PlaySportRoute
  '/arcade_/rooms_/$id': typeof ArcadeRoomsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcade'
    | '/auth'
    | '/compete'
    | '/filters'
    | '/leaderboard'
    | '/upgrade'
    | '/admin'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/arcade/board'
    | '/arcade/connect-four'
    | '/arcade/mastermind'
    | '/arcade/quiz-race'
    | '/arcade/rooms'
    | '/clue/$sport'
    | '/endless/$sport'
    | '/modes/$sport'
    | '/play/$sport'
    | '/arcade/rooms/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcade'
    | '/auth'
    | '/compete'
    | '/filters'
    | '/leaderboard'
    | '/upgrade'
    | '/admin'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/arcade/board'
    | '/arcade/connect-four'
    | '/arcade/mastermind'
    | '/arcade/quiz-race'
    | '/arcade/rooms'
    | '/clue/$sport'
    | '/endless/$sport'
    | '/modes/$sport'
    | '/play/$sport'
    | '/arcade/rooms/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/arcade'
    | '/auth'
    | '/compete'
    | '/filters'
    | '/leaderboard'
    | '/upgrade'
    | '/_authenticated/admin'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/arcade_/board'
    | '/arcade_/connect-four'
    | '/arcade_/mastermind'
    | '/arcade_/quiz-race'
    | '/arcade_/rooms'
    | '/clue/$sport'
    | '/endless/$sport'
    | '/modes/$sport'
    | '/play/$sport'
    | '/arcade_/rooms_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArcadeRoute: typeof ArcadeRoute
  AuthRoute: typeof AuthRoute
  CompeteRoute: typeof CompeteRoute
  FiltersRoute: typeof FiltersRoute
  LeaderboardRoute: typeof LeaderboardRoute
  UpgradeRoute: typeof UpgradeRoute
  ArcadeBoardRoute: typeof ArcadeBoardRoute
  ArcadeConnectFourRoute: typeof ArcadeConnectFourRoute
  ArcadeMastermindRoute: typeof ArcadeMastermindRoute
  ArcadeQuizRaceRoute: typeof ArcadeQuizRaceRoute
  ArcadeRoomsRoute: typeof ArcadeRoomsRoute
  ClueSportRoute: typeof ClueSportRoute
  EndlessSportRoute: typeof EndlessSportRoute
  ModesSportRoute: typeof ModesSportRoute
  PlaySportRoute: typeof PlaySportRoute
  ArcadeRoomsIdRoute: typeof ArcadeRoomsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compete': {
      id: '/compete'
      path: '/compete'
      fullPath: '/compete'
      preLoaderRoute: typeof CompeteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/arcade_/board': {
      id: '/arcade_/board'
      path: '/arcade/board'
      fullPath: '/arcade/board'
      preLoaderRoute: typeof ArcadeBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade_/connect-four': {
      id: '/arcade_/connect-four'
      path: '/arcade/connect-four'
      fullPath: '/arcade/connect-four'
      preLoaderRoute: typeof ArcadeConnectFourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade_/mastermind': {
      id: '/arcade_/mastermind'
      path: '/arcade/mastermind'
      fullPath: '/arcade/mastermind'
      preLoaderRoute: typeof ArcadeMastermindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade_/quiz-race': {
      id: '/arcade_/quiz-race'
      path: '/arcade/quiz-race'
      fullPath: '/arcade/quiz-race'
      preLoaderRoute: typeof ArcadeQuizRaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade_/rooms': {
      id: '/arcade_/rooms'
      path: '/arcade/rooms'
      fullPath: '/arcade/rooms'
      preLoaderRoute: typeof ArcadeRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clue/$sport': {
      id: '/clue/$sport'
      path: '/clue/$sport'
      fullPath: '/clue/$sport'
      preLoaderRoute: typeof ClueSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endless/$sport': {
      id: '/endless/$sport'
      path: '/endless/$sport'
      fullPath: '/endless/$sport'
      preLoaderRoute: typeof EndlessSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes/$sport': {
      id: '/modes/$sport'
      path: '/modes/$sport'
      fullPath: '/modes/$sport'
      preLoaderRoute: typeof ModesSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$sport': {
      id: '/play/$sport'
      path: '/play/$sport'
      fullPath: '/play/$sport'
      preLoaderRoute: typeof PlaySportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade_/rooms_/$id': {
      id: '/arcade_/rooms_/$id'
      path: '/arcade/rooms/$id'
      fullPath: '/arcade/rooms/$id'
      preLoaderRoute: typeof ArcadeRoomsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArcadeRoute: ArcadeRoute,
  AuthRoute: AuthRoute,
  CompeteRoute: CompeteRoute,
  FiltersRoute: FiltersRoute,
  LeaderboardRoute: LeaderboardRoute,
  UpgradeRoute: UpgradeRoute,
  ArcadeBoardRoute: ArcadeBoardRoute,
  ArcadeConnectFourRoute: ArcadeConnectFourRoute,
  ArcadeMastermindRoute: ArcadeMastermindRoute,
  ArcadeQuizRaceRoute: ArcadeQuizRaceRoute,
  ArcadeRoomsRoute: ArcadeRoomsRoute,
  ClueSportRoute: ClueSportRoute,
  EndlessSportRoute: EndlessSportRoute,
  ModesSportRoute: ModesSportRoute,
  PlaySportRoute: PlaySportRoute,
  ArcadeRoomsIdRoute: ArcadeRoomsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
