/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompeteRouteImport } from './routes/compete'
import { Route as FiltersRouteImport } from './routes/filters'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ArcadeIndexRouteImport } from './routes/arcade/index'
import { Route as ArcadeConnectFourRouteImport } from './routes/arcade/connect-four'
import { Route as ClueSportRouteImport } from './routes/clue.$sport'
import { Route as PlaySportRouteImport } from './routes/play.$sport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeteRoute = CompeteRouteImport.update({
  id: '/compete',
  path: '/compete',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltersRoute = FiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArcadeIndexRoute = ArcadeIndexRouteImport.update({
  id: '/arcade/',
  path: '/arcade/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeConnectFourRoute = ArcadeConnectFourRouteImport.update({
  id: '/arcade/connect-four',
  path: '/arcade/connect-four',
  getParentRoute: () => rootRouteImport,
} as any)
const ClueSportRoute = ClueSportRouteImport.update({
  id: '/clue/$sport',
  path: '/clue/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySportRoute = PlaySportRouteImport.update({
  id: '/play/$sport',
  path: '/play/$sport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compete': typeof CompeteRoute
  '/filters': typeof FiltersRoute
  '/leaderboard': typeof LeaderboardRoute
  '/upgrade': typeof UpgradeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/arcade/connect-four': typeof ArcadeConnectFourRoute
  '/clue/$sport': typeof ClueSportRoute
  '/play/$sport': typeof PlaySportRoute
  '/arcade/': typeof ArcadeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compete': typeof CompeteRoute
  '/filters': typeof FiltersRoute
  '/leaderboard': typeof LeaderboardRoute
  '/upgrade': typeof UpgradeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/arcade/connect-four': typeof ArcadeConnectFourRoute
  '/clue/$sport': typeof ClueSportRoute
  '/play/$sport': typeof PlaySportRoute
  '/arcade': typeof ArcadeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compete': typeof CompeteRoute
  '/filters': typeof FiltersRoute
  '/leaderboard': typeof LeaderboardRoute
  '/upgrade': typeof UpgradeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/arcade/connect-four': typeof ArcadeConnectFourRoute
  '/clue/$sport': typeof ClueSportRoute
  '/play/$sport': typeof PlaySportRoute
  '/arcade/': typeof ArcadeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compete'
    | '/filters'
    | '/leaderboard'
    | '/upgrade'
    | '/admin'
    | '/profile'
    | '/arcade/connect-four'
    | '/clue/$sport'
    | '/play/$sport'
    | '/arcade/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compete'
    | '/filters'
    | '/leaderboard'
    | '/upgrade'
    | '/admin'
    | '/profile'
    | '/arcade/connect-four'
    | '/clue/$sport'
    | '/play/$sport'
    | '/arcade'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compete'
    | '/filters'
    | '/leaderboard'
    | '/upgrade'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/arcade/connect-four'
    | '/clue/$sport'
    | '/play/$sport'
    | '/arcade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompeteRoute: typeof CompeteRoute
  FiltersRoute: typeof FiltersRoute
  LeaderboardRoute: typeof LeaderboardRoute
  UpgradeRoute: typeof UpgradeRoute
  ArcadeConnectFourRoute: typeof ArcadeConnectFourRoute
  ClueSportRoute: typeof ClueSportRoute
  PlaySportRoute: typeof PlaySportRoute
  ArcadeIndexRoute: typeof ArcadeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compete': {
      id: '/compete'
      path: '/compete'
      fullPath: '/compete'
      preLoaderRoute: typeof CompeteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/arcade/': {
      id: '/arcade/'
      path: '/arcade'
      fullPath: '/arcade/'
      preLoaderRoute: typeof ArcadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade/connect-four': {
      id: '/arcade/connect-four'
      path: '/arcade/connect-four'
      fullPath: '/arcade/connect-four'
      preLoaderRoute: typeof ArcadeConnectFourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clue/$sport': {
      id: '/clue/$sport'
      path: '/clue/$sport'
      fullPath: '/clue/$sport'
      preLoaderRoute: typeof ClueSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$sport': {
      id: '/play/$sport'
      path: '/play/$sport'
      fullPath: '/play/$sport'
      preLoaderRoute: typeof PlaySportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompeteRoute: CompeteRoute,
  FiltersRoute: FiltersRoute,
  LeaderboardRoute: LeaderboardRoute,
  UpgradeRoute: UpgradeRoute,
  ArcadeConnectFourRoute: ArcadeConnectFourRoute,
  ClueSportRoute: ClueSportRoute,
  PlaySportRoute: PlaySportRoute,
  ArcadeIndexRoute: ArcadeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
