-- Verified depth phase 13: 32 source-backed questions across 8 sports.
with editorial as (select id from public.data_sources where name='Fanzeno sourced editorial' limit 1), seed(sport_slug,category_key,prompt,clue,accepted,display,percentile,source_url,source_title) as (values
('football','europa-league','Which club won the 2021 UEFA Europa League final?','They defeated Manchester United on penalties.','["Villarreal","Villarreal CF"]'::jsonb,'Villarreal',0.12,'https://www.uefa.com/uefaeuropaleague/history/seasons/2021/','UEFA Europa League 2020/21 history'),
('football','world-cup','Which nation won the 2014 men’s FIFA World Cup?','Mario Götze scored the final’s only goal.','["Germany"]'::jsonb,'Germany',0.38,'https://www.fifa.com/tournaments/mens/worldcup/2014brazil','FIFA World Cup Brazil 2014'),
('football','european-championship','Which nation won UEFA Euro 1992 after entering the tournament as a late replacement?','They defeated Germany in the final.','["Denmark"]'::jsonb,'Denmark',0.65,'https://www.uefa.com/uefaeuro/history/seasons/1992/','UEFA Euro 1992 history'),
('football','european-cup','Which club became the first British winner of the European Cup in 1967?','The team was nicknamed the Lisbon Lions.','["Celtic","Celtic FC"]'::jsonb,'Celtic',0.9,'https://www.uefa.com/uefachampionsleague/history/seasons/1966/','UEFA European Cup 1966/67 history'),
('cricket','world-test-championship','Which nation won the 2023 ICC World Test Championship final?','They defeated India at The Oval.','["Australia"]'::jsonb,'Australia',0.12,'https://www.icc-cricket.com/tournaments/world-test-championship','ICC World Test Championship'),
('cricket','champions-trophy','Which nation won the 2017 ICC Champions Trophy?','They defeated India at The Oval.','["Pakistan"]'::jsonb,'Pakistan',0.38,'https://www.icc-cricket.com/tournaments/champions-trophy','ICC Champions Trophy'),
('cricket','womens-world-cup','Which nation won the 2005 ICC Women’s Cricket World Cup?','They defeated India in the final.','["Australia"]'::jsonb,'Australia',0.65,'https://www.icc-cricket.com/tournaments/womens-cricket-worldcup/history','ICC Women’s Cricket World Cup history'),
('cricket','test-records','Who scored the first triple century in Test cricket in 1930?','The England opener made 325 against West Indies.','["Andy Sandham","Sandham"]'::jsonb,'Andy Sandham',0.9,'https://www.icc-cricket.com/about/cricket/history-of-cricket/early-cricket','ICC cricket history'),
('rugby','six-nations','Which nation won the 2022 men’s Six Nations Grand Slam?','They won all five matches.','["France"]'::jsonb,'France',0.12,'https://www.sixnationsrugby.com/en/m6n/championships','Six Nations championship history'),
('rugby','lions','Which team won the British & Irish Lions’ 2013 series in Australia?','The tourists won the deciding Test 41–16.','["British and Irish Lions","British & Irish Lions","Lions"]'::jsonb,'British & Irish Lions',0.38,'https://www.lionsrugby.com/history/','British & Irish Lions history'),
('rugby','world-cup','Which nation won the 2007 men’s Rugby World Cup?','They defeated England in the final without scoring a try.','["South Africa","Springboks"]'::jsonb,'South Africa',0.65,'https://www.rugbyworldcup.com/2019/archive/2007/overview','Rugby World Cup 2007 archive'),
('rugby','world-cup','Who captained Australia to victory at the 1991 Rugby World Cup?','He was a scrum-half.','["Nick Farr-Jones","Nick Farr Jones","Farr-Jones","Farr Jones"]'::jsonb,'Nick Farr-Jones',0.9,'https://www.rugbyworldcup.com/2019/archive/1991/overview','Rugby World Cup 1991 archive'),
('nfl','super-bowl','Which team won Super Bowl LII?','They defeated New England 41–33.','["Philadelphia Eagles","Eagles","Philadelphia"]'::jsonb,'Philadelphia Eagles',0.12,'https://www.nfl.com/super-bowl/history','NFL Super Bowl history'),
('nfl','mvp','Who won the NFL Most Valuable Player award for the 2012 season?','The Minnesota running back returned from knee surgery.','["Adrian Peterson","Peterson"]'::jsonb,'Adrian Peterson',0.38,'https://www.nfl.com/honors/','NFL Honors'),
('nfl','draft','Who was selected first overall in the 1997 NFL Draft?','The St. Louis Rams selected this offensive tackle.','["Orlando Pace","Pace"]'::jsonb,'Orlando Pace',0.65,'https://www.nfl.com/draft/history/fulldraft','NFL Draft history'),
('nfl','super-bowl-mvp','Who became the first and only Super Bowl MVP from the losing team?','A Dallas Cowboys linebacker won the award in Super Bowl V.','["Chuck Howley","Howley"]'::jsonb,'Chuck Howley',0.9,'https://www.nfl.com/super-bowl/history','NFL Super Bowl history'),
('nba','champions','Which team won its first NBA championship in 2019?','They defeated Golden State in six games.','["Toronto Raptors","Raptors","Toronto"]'::jsonb,'Toronto Raptors',0.12,'https://www.nba.com/news/history-nba-champions','NBA champions history'),
('nba','mvp','Who won the 2016–17 NBA Most Valuable Player award?','He averaged a triple-double for Oklahoma City.','["Russell Westbrook","Westbrook"]'::jsonb,'Russell Westbrook',0.38,'https://www.nba.com/news/history-mvp-award-winners','NBA MVP history'),
('nba','mvp','Who won his third consecutive NBA MVP award in the 1985–86 season?','A Boston Celtics forward.','["Larry Bird","Bird"]'::jsonb,'Larry Bird',0.65,'https://www.nba.com/news/history-mvp-award-winners','NBA MVP history'),
('nba','finals-mvp','Who was NBA Finals MVP in 1975?','He led Golden State to a sweep of Washington.','["Rick Barry","Barry"]'::jsonb,'Rick Barry',0.9,'https://www.nba.com/news/history-finals-mvp-winners','NBA Finals MVP history'),
('golf','the-open','Who won The Open Championship in 2021?','He won on his championship debut at Royal St George’s.','["Collin Morikawa","Morikawa"]'::jsonb,'Collin Morikawa',0.12,'https://www.theopen.com/previous-opens','The Open previous championships'),
('golf','ryder-cup','Which team won the 2018 Ryder Cup at Le Golf National?','The hosts won 17½–10½.','["Europe","Team Europe"]'::jsonb,'Europe',0.38,'https://www.rydercup.com/history','Ryder Cup history'),
('golf','the-open','Who won The Open Championship in 2003 on his major debut?','The American won at Royal St George’s.','["Ben Curtis","Curtis"]'::jsonb,'Ben Curtis',0.65,'https://www.theopen.com/previous-opens','The Open previous championships'),
('golf','the-open','Who won The Open Championship in 1951?','The Englishman was known for a distinctive bent-knee swing.','["Max Faulkner","Faulkner"]'::jsonb,'Max Faulkner',0.9,'https://www.theopen.com/previous-opens','The Open previous championships'),
('tennis','us-open-men','Who won the 2022 US Open men’s singles title?','The victory made him the youngest world No. 1 in ATP history.','["Carlos Alcaraz","Alcaraz"]'::jsonb,'Carlos Alcaraz',0.12,'https://www.usopen.org/en_US/visit/history/mschamps.html','US Open men’s champions'),
('tennis','wimbledon','Who won the 2019 Wimbledon women’s singles title?','She defeated Serena Williams in the final.','["Simona Halep","Halep"]'::jsonb,'Simona Halep',0.38,'https://www.wimbledon.com/en_GB/roll_of_honour/ladiessingles.html','Wimbledon ladies’ singles roll of honour'),
('tennis','french-open','Who won the 2004 French Open men’s singles title after losing the first two sets of the final?','The Argentine defeated Guillermo Coria.','["Gaston Gaudio","Gaudio"]'::jsonb,'Gaston Gaudio',0.65,'https://www.rolandgarros.com/en-us/palmares','Roland-Garros roll of honour'),
('tennis','wimbledon','Who won his first Wimbledon men’s singles title in 1976 without losing a set?','The Swedish champion defeated Ilie Năstase.','["Bjorn Borg","Björn Borg","Borg"]'::jsonb,'Bjorn Borg',0.9,'https://www.wimbledon.com/en_GB/roll_of_honour/gentlemenssingles.html','Wimbledon gentlemen’s singles roll of honour'),
('horse-racing','major-races','Which horse won the 2022 Kentucky Derby at odds of 80–1?','Sonny Leon rode the late entry.','["Rich Strike"]'::jsonb,'Rich Strike',0.12,'https://www.kentuckyderby.com/history/year/2022','Kentucky Derby official history'),
('horse-racing','major-races','Which horse won the Grand National in both 2018 and 2019?','Davy Russell rode both victories.','["Tiger Roll"]'::jsonb,'Tiger Roll',0.38,'https://www.thejockeyclub.co.uk/aintree/events-tickets/grand-national/about-the-event/history/','The Jockey Club Grand National history'),
('horse-racing','major-races','Which horse won the 2011 Melbourne Cup?','The French-trained horse won after a photo finish.','["Dunaden"]'::jsonb,'Dunaden',0.65,'https://www.vrc.com.au/melbourne-cup-carnival/history/','Victoria Racing Club Melbourne Cup history'),
('horse-racing','triple-crown','Which horse won the US Triple Crown in 1977?','The unbeaten colt was ridden by Jean Cruguet.','["Seattle Slew"]'::jsonb,'Seattle Slew',0.9,'https://www.belmontstakes.com/history/triple-crown-winners/','Belmont Stakes Triple Crown history')
), validated as (select * from seed where jsonb_typeof(accepted)='array' and jsonb_array_length(accepted)>0 and length(trim(prompt))>=12 and length(trim(clue))>=5 and length(trim(display))>0 and percentile between 0 and 1 and source_url like 'https://%' and not exists(select 1 from jsonb_array_elements_text(accepted) a where length(trim(a))=0))
insert into public.question_bank(sport_id,category_key,question_type,format_key,prompt_i18n,clue_i18n,answer_rule,answer_display_i18n,difficulty_b,difficulty_percentile,editorial_difficulty_percentile,difficulty_confidence,quality_score,ambiguity_score,verification_status,source_id,source_url,source_title,content_hash,reviewed_at,active)
select s.id,v.category_key,'typed_single','classic_trivia',jsonb_build_object('en',v.prompt),jsonb_build_object('en',v.clue),jsonb_build_object('accepted',v.accepted),jsonb_build_object('en',v.display),case when v.percentile<.25 then -1.3 when v.percentile<.5 then -.3 when v.percentile<.75 then .7 else 1.5 end,v.percentile,v.percentile,0,1,0,'verified',editorial.id,v.source_url,v.source_title,encode(extensions.digest(v.prompt,'sha256'),'hex'),now(),true from validated v join public.sports s on s.slug=v.sport_slug cross join editorial on conflict do nothing;
select public.prepare_verified_question_batch('Verified expansion 13 — cups, awards and classic records',32);

-- Correct phase 10 clue for databases where that migration was already applied.
update public.question_bank
set clue_i18n = jsonb_build_object('en','He won the UFC 12 heavyweight tournament.'), reviewed_at = now()
where content_hash = encode(extensions.digest('Who became the inaugural UFC heavyweight champion in 1997?','sha256'),'hex');
