-- Verified depth phase 11: 32 source-backed questions across 8 sports.
with editorial as (select id from public.data_sources where name='Fanzeno sourced editorial' limit 1),
seed(sport_slug,category_key,prompt,clue,accepted,display,percentile,source_url,source_title) as (values
('football','world-cup','Which nation won the 2022 men’s FIFA World Cup?','They defeated France on penalties.','["Argentina"]'::jsonb,'Argentina',0.12,'https://www.fifa.com/tournaments/mens/worldcup/qatar2022','FIFA World Cup Qatar 2022'),
('football','european-championship','Which nation won UEFA Euro 2016?','They beat hosts France in the final.','["Portugal"]'::jsonb,'Portugal',0.38,'https://www.uefa.com/uefaeuro/history/seasons/2016/','UEFA Euro 2016 history'),
('football','champions-league','Which club won the 2004 UEFA Champions League?','José Mourinho managed the winners.','["Porto","FC Porto"]'::jsonb,'FC Porto',0.65,'https://www.uefa.com/uefachampionsleague/history/seasons/2003/','UEFA Champions League 2003/04 history'),
('football','ballon-dor','Who won the 1960 Ballon d’Or?','A Spanish midfielder known as Luisito.','["Luis Suarez","Luis Suárez","Luis Suarez Miramontes","Luis Suárez Miramontes"]'::jsonb,'Luis Suárez',0.9,'https://www.francefootball.fr/ballon-d-or/palmares/','France Football Ballon d’Or winners'),
('cricket','t20-world-cup','Which nation won the 2021 ICC Men’s T20 World Cup?','They defeated New Zealand in the final.','["Australia"]'::jsonb,'Australia',0.12,'https://www.icc-cricket.com/tournaments/t20cricketworldcup/history','ICC Men’s T20 World Cup history'),
('cricket','world-test-championship','Which nation won the inaugural ICC World Test Championship in 2021?','They defeated India at Southampton.','["New Zealand"]'::jsonb,'New Zealand',0.38,'https://www.icc-cricket.com/tournaments/world-test-championship','ICC World Test Championship'),
('cricket','t20-world-cup','Which nation won the inaugural ICC Men’s T20 World Cup in 2007?','They defeated Pakistan in the final.','["India"]'::jsonb,'India',0.65,'https://www.icc-cricket.com/tournaments/t20cricketworldcup/history','ICC Men’s T20 World Cup history'),
('cricket','test-records','Who took the first hat-trick in Test cricket?','The Australian achieved it against England in 1879.','["Fred Spofforth","Spofforth"]'::jsonb,'Fred Spofforth',0.9,'https://www.icc-cricket.com/about/cricket/history-of-cricket/early-cricket','ICC cricket history'),
('rugby','world-cup','Which nation won the 2019 men’s Rugby World Cup?','They defeated England in the final.','["South Africa","Springboks"]'::jsonb,'South Africa',0.12,'https://www.rugbyworldcup.com/2019/','Rugby World Cup 2019'),
('rugby','world-cup','Which nation won the 2015 men’s Rugby World Cup?','They became the first nation to retain the trophy.','["New Zealand","All Blacks"]'::jsonb,'New Zealand',0.38,'https://www.rugbyworldcup.com/2019/archive/2015/overview','Rugby World Cup 2015 archive'),
('rugby','womens-world-cup','Which nation won the inaugural Women’s Rugby World Cup in 1991?','They defeated England in Cardiff.','["United States","USA","United States of America"]'::jsonb,'United States',0.65,'https://www.rugbyworldcup.com/2021/about/history','Women’s Rugby World Cup history'),
('rugby','world-cup','Who captained New Zealand to victory at the inaugural Rugby World Cup in 1987?','He was an Auckland scrum-half.','["David Kirk","Kirk"]'::jsonb,'David Kirk',0.9,'https://www.rugbyworldcup.com/2019/archive/1987/overview','Rugby World Cup 1987 archive'),
('nfl','super-bowl','Which team won Super Bowl LVI?','They defeated Cincinnati at SoFi Stadium.','["Los Angeles Rams","LA Rams","Rams"]'::jsonb,'Los Angeles Rams',0.12,'https://www.nfl.com/super-bowl/history','NFL Super Bowl history'),
('nfl','draft','Who was selected first overall in the 2020 NFL Draft?','The Cincinnati Bengals selected this quarterback.','["Joe Burrow","Burrow"]'::jsonb,'Joe Burrow',0.38,'https://www.nfl.com/draft/history/fulldraft','NFL Draft history'),
('nfl','super-bowl-mvp','Who was MVP of both Super Bowl I and Super Bowl II?','A Green Bay Packers quarterback.','["Bart Starr","Starr"]'::jsonb,'Bart Starr',0.65,'https://www.nfl.com/super-bowl/history','NFL Super Bowl history'),
('nfl','super-bowl','Who started at quarterback for the Chicago Bears in Super Bowl XX?','He wore number 9.','["Jim McMahon","McMahon"]'::jsonb,'Jim McMahon',0.9,'https://www.nfl.com/super-bowl/history','NFL Super Bowl history'),
('nba','champions','Which team won the 2021 NBA championship?','They defeated Phoenix in six games.','["Milwaukee Bucks","Bucks","Milwaukee"]'::jsonb,'Milwaukee Bucks',0.12,'https://www.nba.com/news/history-nba-champions','NBA champions history'),
('nba','mvp','Who won the 2019–20 NBA Most Valuable Player award?','The Milwaukee forward won for a second consecutive season.','["Giannis Antetokounmpo","Giannis","Antetokounmpo"]'::jsonb,'Giannis Antetokounmpo',0.38,'https://www.nba.com/news/history-mvp-award-winners','NBA MVP history'),
('nba','finals-mvp','Who was NBA Finals MVP in 1995?','The Houston centre won the award for a second consecutive year.','["Hakeem Olajuwon","Olajuwon"]'::jsonb,'Hakeem Olajuwon',0.65,'https://www.nba.com/news/history-finals-mvp-winners','NBA Finals MVP history'),
('nba','finals','Which team won the triple-overtime Game 5 of the 1976 NBA Finals?','They defeated the Phoenix Suns 128–126.','["Boston Celtics","Celtics","Boston"]'::jsonb,'Boston Celtics',0.9,'https://www.nba.com/news/history-nba-finals','NBA Finals history'),
('mlb','world-series','Which team won the 2022 World Series?','They defeated Philadelphia in six games.','["Houston Astros","Astros","Houston"]'::jsonb,'Houston Astros',0.12,'https://www.mlb.com/postseason/history/world-series','MLB World Series history'),
('mlb','world-series','Which team won its first World Series in 2019?','They defeated Houston in seven games.','["Washington Nationals","Nationals","Washington"]'::jsonb,'Washington Nationals',0.38,'https://www.mlb.com/postseason/history/world-series','MLB World Series history'),
('mlb','world-series','Which team won the 2001 World Series on a Game 7 walk-off hit?','They defeated the New York Yankees.','["Arizona Diamondbacks","Diamondbacks","Arizona"]'::jsonb,'Arizona Diamondbacks',0.65,'https://www.mlb.com/postseason/history/world-series','MLB World Series history'),
('mlb','world-series','Who hit the walk-off home run that won Game 7 of the 1960 World Series?','The Pittsburgh second baseman led off the ninth inning.','["Bill Mazeroski","Mazeroski"]'::jsonb,'Bill Mazeroski',0.9,'https://www.mlb.com/postseason/history/world-series','MLB World Series history'),
('nhl','stanley-cup','Which team won the 2021 Stanley Cup?','They retained the trophy by defeating Montreal.','["Tampa Bay Lightning","Lightning","Tampa Bay"]'::jsonb,'Tampa Bay Lightning',0.12,'https://www.nhl.com/news/stanley-cup-champions-winners-complete-list','NHL Stanley Cup champions'),
('nhl','stanley-cup','Which team won its first Stanley Cup in 2019?','They defeated Boston in seven games.','["St. Louis Blues","St Louis Blues","Blues"]'::jsonb,'St. Louis Blues',0.38,'https://www.nhl.com/news/stanley-cup-champions-winners-complete-list','NHL Stanley Cup champions'),
('nhl','stanley-cup','Which team remains the most recent Canadian club to win the Stanley Cup, doing so in 1993?','They defeated Los Angeles.','["Montreal Canadiens","Canadiens","Montreal"]'::jsonb,'Montreal Canadiens',0.65,'https://www.nhl.com/news/stanley-cup-champions-winners-complete-list','NHL Stanley Cup champions'),
('nhl','conn-smythe','Who won the 1987 Conn Smythe Trophy despite playing for the losing finalist?','A Philadelphia Flyers goaltender.','["Ron Hextall","Hextall"]'::jsonb,'Ron Hextall',0.9,'https://www.nhl.com/news/conn-smythe-trophy-winners-complete-list','NHL Conn Smythe winners'),
('golf','the-open','Who won The Open Championship in 2022?','The Australian shot a final-round 64 at St Andrews.','["Cameron Smith","Cam Smith","Smith"]'::jsonb,'Cameron Smith',0.12,'https://www.theopen.com/previous-opens','The Open previous championships'),
('golf','masters','Who won the 2019 Masters Tournament?','It was his fifth green jacket.','["Tiger Woods","Woods"]'::jsonb,'Tiger Woods',0.38,'https://www.masters.com/en_US/tournament/past_winners.html','Masters past winners'),
('golf','ryder-cup','Which team won the 1999 Ryder Cup at Brookline?','They completed a famous final-day comeback.','["United States","USA","Team USA","US"]'::jsonb,'United States',0.65,'https://www.rydercup.com/history','Ryder Cup history'),
('golf','the-open','Who won The Open Championship at St Andrews in 1970?','He defeated Doug Sanders in an 18-hole playoff.','["Jack Nicklaus","Nicklaus"]'::jsonb,'Jack Nicklaus',0.9,'https://www.theopen.com/previous-opens','The Open previous championships')
), validated as (
select * from seed where jsonb_typeof(accepted)='array' and jsonb_array_length(accepted)>0 and length(trim(prompt))>=12 and length(trim(clue))>=5 and length(trim(display))>0 and percentile between 0 and 1 and source_url like 'https://%' and not exists(select 1 from jsonb_array_elements_text(accepted) a where length(trim(a))=0)
)
insert into public.question_bank(sport_id,category_key,question_type,format_key,prompt_i18n,clue_i18n,answer_rule,answer_display_i18n,difficulty_b,difficulty_percentile,editorial_difficulty_percentile,difficulty_confidence,quality_score,ambiguity_score,verification_status,source_id,source_url,source_title,content_hash,reviewed_at,active)
select s.id,v.category_key,'typed_single','classic_trivia',jsonb_build_object('en',v.prompt),jsonb_build_object('en',v.clue),jsonb_build_object('accepted',v.accepted),jsonb_build_object('en',v.display),case when v.percentile<.25 then -1.3 when v.percentile<.5 then -.3 when v.percentile<.75 then .7 else 1.5 end,v.percentile,v.percentile,0,1,0,'verified',editorial.id,v.source_url,v.source_title,encode(extensions.digest(v.prompt,'sha256'),'hex'),now(),true from validated v join public.sports s on s.slug=v.sport_slug cross join editorial on conflict do nothing;
select public.prepare_verified_question_batch('Verified expansion 11 — global championships',32);
