-- Verified depth phase 12: 32 source-backed questions across 8 sports.
with editorial as (select id from public.data_sources where name='Fanzeno sourced editorial' limit 1), seed(sport_slug,category_key,prompt,clue,accepted,display,percentile,source_url,source_title) as (values
('tennis','french-open','Who won the 2023 French Open men’s singles title?','The victory gave him a record 23rd men’s major title.','["Novak Djokovic","Novak Đoković","Djokovic","Đoković"]'::jsonb,'Novak Djokovic',0.12,'https://www.rolandgarros.com/en-us/palmares','Roland-Garros roll of honour'),
('tennis','wimbledon','Who won the 2022 Wimbledon women’s singles title?','She represented Kazakhstan.','["Elena Rybakina","Rybakina"]'::jsonb,'Elena Rybakina',0.38,'https://www.wimbledon.com/en_GB/roll_of_honour/ladiessingles.html','Wimbledon ladies’ singles roll of honour'),
('tennis','wimbledon','Who won the 2001 Wimbledon men’s singles title as a wildcard?','The Croatian defeated Patrick Rafter.','["Goran Ivanisevic","Goran Ivanišević","Ivanisevic","Ivanišević"]'::jsonb,'Goran Ivanisevic',0.65,'https://www.wimbledon.com/en_GB/roll_of_honour/gentlemenssingles.html','Wimbledon gentlemen’s singles roll of honour'),
('tennis','french-open','Who became the youngest male Grand Slam singles champion by winning the 1989 French Open?','The American was 17 years old.','["Michael Chang","Chang"]'::jsonb,'Michael Chang',0.9,'https://www.rolandgarros.com/en-us/palmares','Roland-Garros roll of honour'),
('horse-racing','major-races','Which horse won the 2021 Grand National?','Rachael Blackmore became the first female jockey to win the race.','["Minella Times"]'::jsonb,'Minella Times',0.12,'https://www.thejockeyclub.co.uk/aintree/events-tickets/grand-national/about-the-event/history/','The Jockey Club Grand National history'),
('horse-racing','major-races','Which horse won the 2020 Kentucky Derby?','John Velazquez rode the winner.','["Authentic"]'::jsonb,'Authentic',0.38,'https://www.kentuckyderby.com/history/year/2020','Kentucky Derby official history'),
('horse-racing','triple-crown','Which horse won the US Triple Crown in 2018?','Mike Smith rode the unbeaten colt.','["Justify"]'::jsonb,'Justify',0.65,'https://www.belmontstakes.com/history/triple-crown-winners/','Belmont Stakes Triple Crown history'),
('horse-racing','uk-classics','Which horse won the English Triple Crown in 1970?','Lester Piggott rode the colt.','["Nijinsky","Nijinsky II"]'::jsonb,'Nijinsky',0.9,'https://www.thejockeyclub.co.uk/epsom/events-tickets/epsom-derby/history/','The Jockey Club Derby history'),
('nascar','daytona-500','Who won the 2023 Daytona 500?','He won in double overtime.','["Ricky Stenhouse Jr","Ricky Stenhouse Junior","Stenhouse"]'::jsonb,'Ricky Stenhouse Jr.',0.12,'https://www.nascar.com/gallery/daytona-500-champions/','NASCAR Daytona 500 champions'),
('nascar','cup-series','Who won the 2019 NASCAR Cup Series championship?','It was his second Cup title.','["Kyle Busch","Busch"]'::jsonb,'Kyle Busch',0.38,'https://www.nascar.com/gallery/all-time-nascar-cup-series-champions/','NASCAR Cup champions'),
('nascar','cup-series','Who won the inaugural Chase for the Cup championship in 2004?','He drove the No. 97 Ford.','["Kurt Busch","Busch"]'::jsonb,'Kurt Busch',0.65,'https://www.nascar.com/gallery/all-time-nascar-cup-series-champions/','NASCAR Cup champions'),
('nascar','daytona-500','Who won the 1988 Daytona 500 ahead of his son Davey?','The winner drove a Buick.','["Bobby Allison","Allison"]'::jsonb,'Bobby Allison',0.9,'https://www.nascar.com/gallery/daytona-500-champions/','NASCAR Daytona 500 champions'),
('indycar','indy-500','Who won the 2022 Indianapolis 500?','The Swedish driver held off Pato O’Ward.','["Marcus Ericsson","Ericsson"]'::jsonb,'Marcus Ericsson',0.12,'https://www.indianapolismotorspeedway.com/events/indy500/history/winners','Indianapolis 500 winners'),
('indycar','indy-500','Who won the 2019 Indianapolis 500?','The French driver started from pole.','["Simon Pagenaud","Pagenaud"]'::jsonb,'Simon Pagenaud',0.38,'https://www.indianapolismotorspeedway.com/events/indy500/history/winners','Indianapolis 500 winners'),
('indycar','indy-500','Who won the 2001 Indianapolis 500 as a rookie?','A Brazilian driver for Team Penske.','["Helio Castroneves","Hélio Castroneves","Castroneves"]'::jsonb,'Helio Castroneves',0.65,'https://www.indianapolismotorspeedway.com/events/indy500/history/winners','Indianapolis 500 winners'),
('indycar','indy-500','Who won the 1965 Indianapolis 500 in a rear-engined Lotus?','He was a Formula One world champion from Scotland.','["Jim Clark","Clark"]'::jsonb,'Jim Clark',0.9,'https://www.indianapolismotorspeedway.com/events/indy500/history/winners','Indianapolis 500 winners'),
('motogp','world-champions','Who won the 2019 MotoGP World Championship?','The Honda rider secured his sixth premier-class title.','["Marc Marquez","Marc Márquez","Marquez","Márquez"]'::jsonb,'Marc Marquez',0.12,'https://www.motogp.com/en/world-champions','MotoGP world champions'),
('motogp','world-champions','Who won the 2017 MotoGP World Championship?','He defeated Andrea Dovizioso in the title race.','["Marc Marquez","Marc Márquez","Marquez","Márquez"]'::jsonb,'Marc Marquez',0.38,'https://www.motogp.com/en/world-champions','MotoGP world champions'),
('motogp','world-champions','Who won the 2007 MotoGP World Championship?','An Australian Ducati rider.','["Casey Stoner","Stoner"]'::jsonb,'Casey Stoner',0.65,'https://www.motogp.com/en/world-champions','MotoGP world champions'),
('motogp','world-champions','Who won the 1981 500cc world championship?','An Italian Suzuki rider.','["Marco Lucchinelli","Lucchinelli"]'::jsonb,'Marco Lucchinelli',0.9,'https://www.motogp.com/en/world-champions','MotoGP world champions'),
('superbikes','world-champions','Who won the 2019 World Superbike Championship?','It was his fifth consecutive title.','["Jonathan Rea","Rea"]'::jsonb,'Jonathan Rea',0.12,'https://www.worldsbk.com/en/results%20statistics','WorldSBK results and statistics'),
('superbikes','world-champions','Who won the 2011 World Superbike Championship?','The Spanish rider raced for Ducati.','["Carlos Checa","Checa"]'::jsonb,'Carlos Checa',0.38,'https://www.worldsbk.com/en/results%20statistics','WorldSBK results and statistics'),
('superbikes','world-champions','Who won the 2002 World Superbike Championship after a dramatic final round at Imola?','An American Honda rider.','["Colin Edwards","Edwards"]'::jsonb,'Colin Edwards',0.65,'https://www.worldsbk.com/en/results%20statistics','WorldSBK results and statistics'),
('superbikes','world-champions','Who won the 1990 World Superbike Championship?','A French Ducati rider.','["Raymond Roche","Roche"]'::jsonb,'Raymond Roche',0.9,'https://www.worldsbk.com/en/results%20statistics','WorldSBK results and statistics'),
('boxing-pro','heavyweight','Who handed Anthony Joshua his first professional defeat in 2019?','The Mexican-American won by seventh-round stoppage.','["Andy Ruiz Jr","Andy Ruiz Junior","Andy Ruiz","Ruiz"]'::jsonb,'Andy Ruiz Jr.',0.12,'https://www.wboboxing.com/boxing-history/','WBO boxing history'),
('boxing-pro','heavyweight','Who became undisputed heavyweight champion by defeating Evander Holyfield in their 1999 rematch?','The British boxer won by unanimous decision.','["Lennox Lewis","Lewis"]'::jsonb,'Lennox Lewis',0.38,'https://www.ibhof.com/pages/about/inductees/modern/lewis.html','International Boxing Hall of Fame'),
('boxing-pro','heavyweight','Who defeated Evander Holyfield to win the undisputed heavyweight championship in 1992?','He won by unanimous decision.','["Riddick Bowe","Bowe"]'::jsonb,'Riddick Bowe',0.65,'https://www.ibhof.com/pages/about/inductees/modern/bowe.html','International Boxing Hall of Fame'),
('boxing-pro','heavyweight','Who became the first Black world heavyweight champion in 1908?','He defeated Tommy Burns in Sydney.','["Jack Johnson","Johnson"]'::jsonb,'Jack Johnson',0.9,'https://www.ibhof.com/pages/about/inductees/oldtimer/johnson.html','International Boxing Hall of Fame'),
('ufc','lightweight','Who won the vacant UFC lightweight title by defeating Michael Chandler in 2021?','He won by second-round stoppage.','["Charles Oliveira","Oliveira"]'::jsonb,'Charles Oliveira',0.12,'https://www.ufc.com/athlete/charles-oliveira','UFC athlete record'),
('ufc','champions','Who defeated Tyron Woodley to win the UFC welterweight title in 2019?','The Nigerian-American won by unanimous decision.','["Kamaru Usman","Usman"]'::jsonb,'Kamaru Usman',0.38,'https://www.ufc.com/athlete/kamaru-usman','UFC athlete record'),
('ufc','champions','Who became the first UFC welterweight champion in 1998?','He won the title at UFC Brazil.','["Pat Miletich","Miletich"]'::jsonb,'Pat Miletich',0.65,'https://www.ufc.com/history','UFC history'),
('ufc','tournaments','Who won the UFC 6 tournament in 1995?','The Russian defeated Tank Abbott in the final.','["Oleg Taktarov","Taktarov"]'::jsonb,'Oleg Taktarov',0.9,'https://www.ufc.com/history','UFC history')
), validated as (select * from seed where jsonb_typeof(accepted)='array' and jsonb_array_length(accepted)>0 and length(trim(prompt))>=12 and length(trim(clue))>=5 and length(trim(display))>0 and percentile between 0 and 1 and source_url like 'https://%' and not exists(select 1 from jsonb_array_elements_text(accepted) a where length(trim(a))=0))
insert into public.question_bank(sport_id,category_key,question_type,format_key,prompt_i18n,clue_i18n,answer_rule,answer_display_i18n,difficulty_b,difficulty_percentile,editorial_difficulty_percentile,difficulty_confidence,quality_score,ambiguity_score,verification_status,source_id,source_url,source_title,content_hash,reviewed_at,active)
select s.id,v.category_key,'typed_single','classic_trivia',jsonb_build_object('en',v.prompt),jsonb_build_object('en',v.clue),jsonb_build_object('accepted',v.accepted),jsonb_build_object('en',v.display),case when v.percentile<.25 then -1.3 when v.percentile<.5 then -.3 when v.percentile<.75 then .7 else 1.5 end,v.percentile,v.percentile,0,1,0,'verified',editorial.id,v.source_url,v.source_title,encode(extensions.digest(v.prompt,'sha256'),'hex'),now(),true from validated v join public.sports s on s.slug=v.sport_slug cross join editorial on conflict do nothing;
select public.prepare_verified_question_batch('Verified expansion 12 — racing, combat and racquet history',32);
