-- v0.8: competition hierarchy (category / format / level), country grouping, new sports, ad analytics
alter table public.competitions
  add column if not exists category_key text,
  add column if not exists category_label text,
  add column if not exists format_key text,
  add column if not exists level_key text,
  add column if not exists parent_competition_id uuid references public.competitions(id);
create index if not exists competition_hierarchy_lookup on public.competitions(sport_id,country_code,category_key,format_key,active);

insert into public.sports(slug,name,accent,enabled,sort_order,historical_from,olympic_classification) values
('snooker','Snooker','#35C98B',true,80,'1900-01-01','none'),
('darts','Darts','#FF5B71',true,81,'1900-01-01','none'),
('horse-racing','Horse Racing','#D9A441',true,82,'1900-01-01','none'),
('f1','Formula 1','#FF3048',true,83,'1950-01-01','none'),
('nascar','NASCAR','#4DA3FF',true,84,'1948-01-01','none'),
('indycar','IndyCar','#8B7CFF',true,85,'1909-01-01','none'),
('motogp','MotoGP','#FF7043',true,86,'1949-01-01','none'),
('superbikes','Superbikes','#35B8D0',true,87,'1976-01-01','none'),
('boxing-pro','Boxing','#F0B84B',true,88,'1900-01-01','none'),
('ufc','UFC / MMA','#D75555',true,89,'1993-01-01','none')
on conflict(slug) do update set name=excluded.name, accent=excluded.accent, enabled=true, sort_order=excluded.sort_order;

with src(sport_slug,slug,name,short_name,region,competition_type,category_label,category_key,level_key,country_code,sort_order) as (values
('football','epl','Premier League','EPL','England','league','Domestic leagues','domestic-leagues',null,'GB',100),
('football','championship','EFL Championship','EFL','England','league','Domestic leagues','domestic-leagues',null,'GB',101),
('football','laliga','La Liga','LAL','Spain','league','Domestic leagues','domestic-leagues',null,'ES',102),
('football','bundesliga','Bundesliga','BUN','Germany','league','Domestic leagues','domestic-leagues',null,'DE',103),
('football','seriea','Serie A','SEA','Italy','league','Domestic leagues','domestic-leagues',null,'IT',104),
('football','ligue1','Ligue 1','L1','France','league','Domestic leagues','domestic-leagues',null,'FR',105),
('football','ucl','UEFA Champions League','UCL','Europe','cup','Continental cups','continental-cups',null,null,106),
('football','uel','UEFA Europa League','UEL','Europe','cup','Continental cups','continental-cups',null,null,107),
('football','fairs-cup','Inter-Cities Fairs Cup','ICFC','Europe','cup','Historic cups','historic-cups',null,null,108),
('football','uefa-cup','UEFA Cup','UC','Europe','cup','Historic cups','historic-cups',null,null,109),
('football','cup-winners-cup','Cup Winners’ Cup','CWC','Europe','cup','Historic cups','historic-cups',null,null,110),
('football','worldcup','FIFA World Cup','WC','International','event','International','international',null,null,111),
('football','uefa-euros','UEFA European Championship','EURO','International','event','International','international',null,null,112),
('football','ballon-dor','Ballon d’Or','BDO','World','event','Awards','awards',null,null,113),
('cricket','tests','Test matches','TEST','International','format','International cricket','international-cricket','Test',null,114),
('cricket','odi','One Day Internationals','ODI','International','format','International cricket','international-cricket','One day',null,115),
('cricket','t20i','T20 Internationals','T20I','International','format','International cricket','international-cricket','T20',null,116),
('cricket','county-championship','County Championship','CC','England','league','First-class cricket','first-class-cricket','First class','GB',117),
('cricket','sheffield-shield','Sheffield Shield','SS','Australia','league','First-class cricket','first-class-cricket','First class','AU',118),
('cricket','quaid-e-azam','Quaid-e-Azam Trophy','QEA','Pakistan','league','First-class cricket','first-class-cricket','First class','PK',119),
('cricket','ranji-trophy','Ranji Trophy','RANJI','India','league','First-class cricket','first-class-cricket','First class','IN',120),
('cricket','one-day-cup','One-Day Cup','ODC','England','league','Domestic one day','domestic-one-day','List A','GB',121),
('cricket','marsh-cup','Australia Domestic One-Day Cup','ODC','Australia','league','Domestic one day','domestic-one-day','List A','AU',122),
('cricket','pakistan-cup','Pakistan Cup','PAK CUP','Pakistan','league','Domestic one day','domestic-one-day','List A','PK',123),
('cricket','ipl','Indian Premier League','IPL','India','league','T20 leagues','t20-leagues','T20','IN',124),
('cricket','bbl','Big Bash League','BBL','Australia','league','T20 leagues','t20-leagues','T20','AU',125),
('cricket','psl','Pakistan Super League','PSL','Pakistan','league','T20 leagues','t20-leagues','T20','PK',126),
('cricket','vitality-blast','T20 Blast','BLAST','England','league','T20 leagues','t20-leagues','T20','GB',127),
('cricket','cpl','Caribbean Premier League','CPL','Caribbean','league','T20 leagues','t20-leagues','T20',null,128),
('cricket','sa20','SA20','SA20','South Africa','league','T20 leagues','t20-leagues','T20','ZA',129),
('cricket','hundred-men','The Hundred Men','100','England','league','The Hundred','the-hundred','100-ball','GB',130),
('cricket','hundred-women','The Hundred Women','100W','England','league','The Hundred','the-hundred','100-ball','GB',131),
('cricket','ashes','The Ashes','ASH','England/Australia','tour','Series & tournaments','series-tournaments','Test',null,132),
('cricket','cricket-world-cup','Cricket World Cup','CWC','International','event','Series & tournaments','series-tournaments','One day',null,133),
('cricket','t20-world-cup','T20 World Cup','T20WC','International','event','Series & tournaments','series-tournaments','T20',null,134),
('rugby','sixnations','Six Nations','6N','Europe','event','International','international',null,null,135),
('rugby','rwc','Rugby World Cup','RWC','World','event','International','international',null,null,136),
('rugby','premrugby','Premiership Rugby','PR','England','league','Domestic leagues','domestic-leagues',null,'GB',137),
('rugby','urc','United Rugby Championship','URC','Europe/South Africa','league','Domestic leagues','domestic-leagues',null,null,138),
('rugby','top14','Top 14','T14','France','league','Domestic leagues','domestic-leagues',null,'FR',139),
('rugby','superrugby','Super Rugby Pacific','SRP','Pacific','league','Domestic leagues','domestic-leagues',null,null,140),
('rugby','npc','National Provincial Championship','NPC','New Zealand','event','New Zealand rugby','new-zealand-rugby',null,'NZ',141),
('rugby','all-blacks','All Blacks Tests','NZ','New Zealand','event','New Zealand rugby','new-zealand-rugby',null,'NZ',142),
('afl','afl','Australian Football League','AFL','Australia','league','Senior leagues','senior-leagues',null,null,143),
('afl','aflw','AFL Women’s','AFLW','Australia','league','Senior leagues','senior-leagues',null,null,144),
('afl','brownlow','Brownlow Medal','BRN','Australia','event','Awards','awards',null,null,145),
('nfl','nfl','National Football League','NFL','USA','league','League','league',null,null,146),
('nfl','afc','AFC','AFC','USA','format','Conferences','conferences',null,null,147),
('nfl','nfc','NFC','NFC','USA','format','Conferences','conferences',null,null,148),
('nfl','superbowl','Super Bowl','SB','USA','event','Postseason & honours','postseason-honours',null,null,149),
('mlb','mlb','Major League Baseball','MLB','USA','league','League','league',null,null,150),
('mlb','american-league','American League','AL','USA','format','Leagues & divisions','leagues-divisions',null,null,151),
('mlb','national-league','National League','NL','USA','format','Leagues & divisions','leagues-divisions',null,null,152),
('mlb','worldseries','World Series','WS','USA','event','Postseason & honours','postseason-honours',null,null,153),
('nhl','nhl','National Hockey League','NHL','North America','league','League','league',null,null,154),
('nhl','eastern','Eastern Conference','EAST','North America','format','Conferences','conferences',null,null,155),
('nhl','western','Western Conference','WEST','North America','format','Conferences','conferences',null,null,156),
('nhl','stanley','Stanley Cup','SC','North America','event','Postseason & honours','postseason-honours',null,null,157),
('nba','nba','National Basketball Association','NBA','USA','league','Leagues','leagues',null,null,158),
('nba','wnba','Women’s NBA','WNBA','USA','league','Leagues','leagues',null,null,159),
('nba','nba-east','Eastern Conference','EAST','USA','format','Conferences','conferences',null,null,160),
('nba','nba-west','Western Conference','WEST','USA','format','Conferences','conferences',null,null,161),
('nba','nba-finals','NBA Finals','FIN','USA','event','Postseason & honours','postseason-honours',null,null,162),
('tennis','atp','ATP Tour','ATP','International','tour','Tours','tours',null,null,163),
('tennis','wta','WTA Tour','WTA','International','tour','Tours','tours',null,null,164),
('tennis','wimbledon','Wimbledon','WIM','UK','event','Grand Slams','grand-slams',null,null,165),
('tennis','australianopen','Australian Open','AO','Australia','event','Grand Slams','grand-slams',null,null,166),
('tennis','rolandgarros','Roland-Garros','RG','France','event','Grand Slams','grand-slams',null,null,167),
('tennis','usopen-tennis','US Open','USO','USA','event','Grand Slams','grand-slams',null,null,168),
('tennis','davis-cup','Davis Cup','DC','International','event','Team events','team-events',null,null,169),
('tennis','billie-jean-king-cup','Billie Jean King Cup','BJK','International','event','Team events','team-events',null,null,170),
('golf','pga','PGA Tour','PGA','USA','tour','Tours','tours',null,null,171),
('golf','dpworld','DP World Tour','DPWT','International','tour','Tours','tours',null,null,172),
('golf','lpga','LPGA Tour','LPGA','International','tour','Tours','tours',null,null,173),
('golf','masters','The Masters','MAS','USA','event','Men’s majors','men-s-majors',null,null,174),
('golf','pga-championship','PGA Championship','PGA','USA','event','Men’s majors','men-s-majors',null,null,175),
('golf','us-open-golf','U.S. Open','USO','USA','event','Men’s majors','men-s-majors',null,null,176),
('golf','open','The Open Championship','OPEN','UK','event','Men’s majors','men-s-majors',null,null,177),
('golf','rydercup','Ryder Cup','RC','Europe/USA','event','Team events','team-events',null,null,178),
('snooker','world-snooker-tour','World Snooker Tour','WST','International','tour','Tour','tour',null,null,179),
('snooker','world-snooker-championship','World Snooker Championship','WSC','England','event','Triple Crown','triple-crown',null,null,180),
('snooker','uk-championship','UK Championship','UK','UK','event','Triple Crown','triple-crown',null,null,181),
('snooker','masters-snooker','The Masters','MAS','England','event','Triple Crown','triple-crown',null,null,182),
('darts','pdc','Professional Darts Corporation','PDC','International','format','Organisations','organisations',null,null,183),
('darts','wdf','World Darts Federation','WDF','International','format','Organisations','organisations',null,null,184),
('darts','pdc-worlds','PDC World Championship','PDC WC','England','event','Majors','majors',null,null,185),
('darts','premier-league-darts','Premier League Darts','PLD','International','event','Majors','majors',null,null,186),
('horse-racing','uk-flat','UK Flat Racing','UK FLAT','UK','league','UK racing','uk-racing',null,'GB',187),
('horse-racing','uk-jumps','UK National Hunt','JUMPS','UK','league','UK racing','uk-racing',null,'GB',188),
('horse-racing','royal-ascot','Royal Ascot','ASCOT','UK','event','UK festivals','uk-festivals',null,'GB',189),
('horse-racing','cheltenham','Cheltenham Festival','CHELT','UK','event','UK festivals','uk-festivals',null,'GB',190),
('horse-racing','us-triple-crown','US Triple Crown','TC','USA','league','USA racing','usa-racing',null,'US',191),
('horse-racing','breeders-cup','Breeders’ Cup','BC','USA','event','USA racing','usa-racing',null,'US',192),
('horse-racing','australian-racing','Australian Racing','AUS','Australia','league','Australian racing','australian-racing',null,'AU',193),
('horse-racing','melbourne-cup','Melbourne Cup','MC','Australia','event','Australian majors','australian-majors',null,'AU',194),
('f1','formula-one','Formula One World Championship','F1','International','event','Championship','championship',null,null,195),
('f1','f1-constructors','Constructors’ Championship','WCC','International','event','Teams & constructors','teams-constructors',null,null,196),
('nascar','nascar-cup','NASCAR Cup Series','CUP','USA','event','National series','national-series',null,null,197),
('nascar','nascar-xfinity','NASCAR Xfinity Series','XFINITY','USA','event','National series','national-series',null,null,198),
('indycar','indycar-series','IndyCar Series','INDYCAR','USA','league','Championship','championship',null,null,199),
('indycar','indy-500','Indianapolis 500','INDY 500','USA','event','Major races','major-races',null,null,200),
('motogp','motogp','MotoGP World Championship','MOTOGP','International','event','Classes','classes',null,null,201),
('motogp','moto2','Moto2','MOTO2','International','format','Classes','classes',null,null,202),
('superbikes','world-superbike','Superbike World Championship','WSBK','International','event','Championships','championships',null,null,203),
('superbikes','british-superbike','British Superbike Championship','BSB','UK','event','Championships','championships',null,'GB',204),
('boxing-pro','boxing-heavyweight','Heavyweight','HW','International','format','Weight classes','weight-classes',null,null,205),
('boxing-pro','boxing-middleweight','Middleweight','MW','International','format','Weight classes','weight-classes',null,null,206),
('boxing-pro','boxing-welterweight','Welterweight','WW','International','format','Weight classes','weight-classes',null,null,207),
('boxing-pro','wbc','WBC','WBC','International','format','Governing bodies','governing-bodies',null,null,208),
('boxing-pro','wba','WBA','WBA','International','format','Governing bodies','governing-bodies',null,null,209),
('boxing-pro','ibf','IBF','IBF','International','format','Governing bodies','governing-bodies',null,null,210),
('boxing-pro','wbo','WBO','WBO','International','format','Governing bodies','governing-bodies',null,null,211),
('ufc','ufc-heavyweight','UFC Heavyweight','HW','International','format','Men’s divisions','men-s-divisions',null,null,212),
('ufc','ufc-lightweight','UFC Lightweight','LW','International','format','Men’s divisions','men-s-divisions',null,null,213),
('ufc','ufc-welterweight','UFC Welterweight','WW','International','format','Men’s divisions','men-s-divisions',null,null,214),
('ufc','ufc-womens-flyweight','UFC Women’s Flyweight','WFLY','International','format','Women’s divisions','women-s-divisions',null,null,215),
('ufc','ufc-events','UFC numbered events','UFC','International','event','Events','events',null,null,216)
)
insert into public.competitions(sport_id,slug,name,short_name,region,competition_type,category_label,category_key,level_key,country_code,sort_order,active)
select s.id,src.slug,src.name,src.short_name,src.region,src.competition_type,src.category_label,src.category_key,src.level_key,src.country_code,src.sort_order,true
from src join public.sports s on s.slug=src.sport_slug
on conflict(sport_id,slug) do update set
  category_label=excluded.category_label,
  category_key=excluded.category_key,
  level_key=excluded.level_key,
  country_code=coalesce(public.competitions.country_code,excluded.country_code),
  short_name=coalesce(public.competitions.short_name,excluded.short_name),
  active=true;

update public.competitions set
  category_key=coalesce(category_key, case competition_type when 'league' then 'domestic-leagues' when 'cup' then 'cups' when 'tour' then 'tours' when 'format' then 'formats' else 'events' end),
  category_label=coalesce(category_label, case competition_type when 'league' then 'Domestic leagues' when 'cup' then 'Cups' when 'tour' then 'Tours' when 'format' then 'Formats' else 'Events' end)
where category_key is null or category_label is null;

create table if not exists public.ad_events(
  id bigint generated always as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  session_id uuid,
  placement text not null,
  ad_unit_id text not null,
  event_type text not null check(event_type in('request','fill','impression','click','revenue')),
  network text,
  currency char(3),
  revenue_micros bigint,
  occurred_at timestamptz not null default now()
);
grant insert on public.ad_events to anon, authenticated;
grant select on public.ad_events to authenticated;
grant all on public.ad_events to service_role;
create index if not exists ad_events_reporting on public.ad_events(placement,event_type,occurred_at desc);
alter table public.ad_events enable row level security;
create policy "own ad event insert" on public.ad_events for insert to anon, authenticated with check(profile_id is null or profile_id=auth.uid());
create policy "staff ad reporting" on public.ad_events for select to authenticated using(public.has_staff_role());