-- Verified depth phase 6: a broader 16-question sports batch.
with editorial as (select id from public.data_sources where name='Fanzeno sourced editorial' limit 1),
seed(sport_slug,category_key,prompt,clue,accepted,display,percentile,source_url,source_title) as (values
('football','world-cup','Who scored a hat-trick in the 1966 men''s World Cup final?','The England striker scored three times against West Germany.','["Geoff Hurst","Sir Geoff Hurst","Hurst"]'::jsonb,'Geoff Hurst',.38,'https://www.fifa.com/tournaments/mens/worldcup/1966england','FIFA 1966 World Cup'),
('football','champions-league','Which club won the 2005 UEFA Champions League final in Istanbul?','They recovered from three goals down against AC Milan.','["Liverpool","Liverpool FC","LFC"]'::jsonb,'Liverpool',.27,'https://www.uefa.com/uefachampionsleague/history/seasons/2004/','UEFA Champions League 2004/05'),
('cricket','ashes','Who scored 766 runs in the 2010–11 Ashes series?','The England opener made three centuries in the series.','["Alastair Cook","Sir Alastair Cook","Cook"]'::jsonb,'Alastair Cook',.63,'https://www.ecb.co.uk/england/men','England and Wales Cricket Board'),
('cricket','world-cup','Who captained Pakistan to the 1992 men''s Cricket World Cup title?','He later became the country''s prime minister.','["Imran Khan","Imran Ahmed Khan Niazi","Khan"]'::jsonb,'Imran Khan',.43,'https://www.icc-cricket.com/tournaments/cricketworldcup','ICC Cricket World Cup'),
('rugby','world-cup','Which nation won the first men''s Rugby World Cup in 1987?','They defeated France in the Auckland final.','["New Zealand","All Blacks","New Zealand All Blacks"]'::jsonb,'New Zealand',.41,'https://www.rugbyworldcup.com/1987','Rugby World Cup 1987'),
('nfl','super-bowl','Which quarterback was MVP of Super Bowl XLIV?','He led New Orleans to its first championship.','["Drew Brees","Brees","Drew Christopher Brees"]'::jsonb,'Drew Brees',.52,'https://www.nfl.com/super-bowl/history','NFL Super Bowl history'),
('nba','finals','Who was Finals MVP when Toronto won the NBA title in 2019?','The forward joined the Raptors before that season.','["Kawhi Leonard","Leonard","Kawhi Anthony Leonard"]'::jsonb,'Kawhi Leonard',.39,'https://www.nba.com/news/history-finals-mvp-winners','NBA Finals MVP history'),
('mlb','world-series','Which team broke an 86-year title drought by winning the 2004 World Series?','They swept St Louis in the final series.','["Boston Red Sox","Red Sox","Boston"]'::jsonb,'Boston Red Sox',.36,'https://www.mlb.com/postseason/history/world-series','MLB World Series history'),
('nhl','stanley-cup','Which franchise won the Stanley Cup in 2009?','Sidney Crosby captained the champions.','["Pittsburgh Penguins","Penguins","Pittsburgh","Pens"]'::jsonb,'Pittsburgh Penguins',.53,'https://www.nhl.com/news/stanley-cup-champions-list-287705398','NHL Stanley Cup champions'),
('tennis','wimbledon','Who won the 2001 Wimbledon men''s singles title as a wildcard?','The Croatian defeated Patrick Rafter in five sets.','["Goran Ivanisevic","Goran Ivanišević","Ivanisevic","Ivanišević"]'::jsonb,'Goran Ivanišević',.59,'https://www.wimbledon.com/en_GB/draws_archive/champions/champions.html','Wimbledon champions'),
('golf','ryder-cup','Which team completed the Miracle at Medinah comeback in the 2012 Ryder Cup?','They began the final day four points behind.','["Europe","Team Europe","European team"]'::jsonb,'Europe',.48,'https://www.rydercup.com/history','Ryder Cup history'),
('f1','world-champions','Who won the 1992 Formula One World Drivers'' Championship?','The Williams driver secured the title at the Hungarian Grand Prix.','["Nigel Mansell","Mansell","Nigel Ernest James Mansell"]'::jsonb,'Nigel Mansell',.55,'https://www.formula1.com/en/results/1992/drivers','Formula 1 1992 standings'),
('darts','world-championship','Who won the 2003 PDC World Darts Championship?','The Canadian defeated Phil Taylor in the final.','["John Part","Part","Darth Maple"]'::jsonb,'John Part',.68,'https://www.pdc.tv/tournament/paddy-power-world-darts-championship','PDC World Championship'),
('snooker','world-championship','Who won the 1986 World Snooker Championship?','He defeated Steve Davis 18–12 in the final.','["Joe Johnson","Johnson","Joseph Johnson"]'::jsonb,'Joe Johnson',.72,'https://www.wst.tv/worldchampionship','World Snooker Tour championship'),
('boxing-pro','heavyweight','Who defeated George Foreman in the Rumble in the Jungle?','The bout took place in Kinshasa in 1974.','["Muhammad Ali","Ali","Cassius Clay","Cassius Marcellus Clay Jr"]'::jsonb,'Muhammad Ali',.29,'https://www.wboboxing.com/boxing-history/','World Boxing Organization history'),
('ufc','champions','Who became the inaugural UFC women''s bantamweight champion?','She was presented with the title before her first UFC bout.','["Ronda Rousey","Rousey","Ronda Jean Rousey"]'::jsonb,'Ronda Rousey',.56,'https://www.ufc.com/athlete/ronda-rousey','UFC athlete profile')
)
insert into public.question_bank(sport_id,category_key,question_type,format_key,prompt_i18n,clue_i18n,answer_rule,answer_display_i18n,difficulty_b,difficulty_percentile,editorial_difficulty_percentile,difficulty_confidence,quality_score,ambiguity_score,verification_status,source_id,source_url,source_title,content_hash,reviewed_at,active)
select s.id,seed.category_key,'typed_single','classic_trivia',jsonb_build_object('en',seed.prompt),jsonb_build_object('en',seed.clue),jsonb_build_object('accepted',seed.accepted),jsonb_build_object('en',seed.display),case when seed.percentile<.25 then -1.3 when seed.percentile<.5 then -.3 when seed.percentile<.75 then .7 else 1.5 end,seed.percentile,seed.percentile,0,1,0,'verified',editorial.id,seed.source_url,seed.source_title,encode(extensions.digest(seed.prompt,'sha256'),'hex'),now(),true
from seed join public.sports s on s.slug=seed.sport_slug cross join editorial on conflict do nothing;
select public.prepare_verified_question_batch('Verified expansion 6 — global sporting history',16);
