-- Verified depth phase 10: 64 source-backed questions across 16 sports.
-- Balanced at 16 questions per difficulty tier, with defensive content validation.
with editorial as (select id from public.data_sources where name='Fanzeno sourced editorial' limit 1),
seed(sport_slug,category_key,prompt,clue,accepted,display,percentile,source_url,source_title) as (values
('football','womens-world-cup','Which nation won the 2023 FIFA Women’s World Cup?','They defeated England in the final.','["Spain"]'::jsonb,'Spain',0.12,'https://www.fifa.com/tournaments/womens/womensworldcup/australia-new-zealand2023','FIFA Women’s World Cup 2023'),
('football','champions-league','Which club won the 2005 UEFA Champions League final after trailing 3–0 at half-time?','The final was played in Istanbul.','["Liverpool","Liverpool FC"]'::jsonb,'Liverpool',0.38,'https://www.uefa.com/uefachampionsleague/history/seasons/2004/','UEFA Champions League 2004/05 history'),
('football','cup-winners-cup','Which club won the 1995 European Cup Winners’ Cup?','Nayim scored from long range in extra time.','["Real Zaragoza","Zaragoza"]'::jsonb,'Real Zaragoza',0.65,'https://www.uefa.com/uefachampionsleague/history/','UEFA competition history'),
('football','africa-cup-of-nations','Which nation won the 1972 Africa Cup of Nations?','They were then known as Congo-Brazzaville.','["Congo","Republic of the Congo","Congo-Brazzaville"]'::jsonb,'Congo',0.9,'https://www.cafonline.com/caf-africa-cup-of-nations/history/','CAF Africa Cup of Nations history'),
('cricket','t20-world-cup','Which nation won the 2016 ICC Men’s T20 World Cup?','Carlos Brathwaite hit four consecutive sixes in the final over.','["West Indies","Windies"]'::jsonb,'West Indies',0.12,'https://www.icc-cricket.com/tournaments/t20cricketworldcup/history','ICC Men’s T20 World Cup history'),
('cricket','the-hundred','Which team won the inaugural men’s Hundred competition in 2021?','They beat Birmingham Phoenix in the final.','["Southern Brave","The Southern Brave"]'::jsonb,'Southern Brave',0.38,'https://www.thehundred.com/history','The Hundred history'),
('cricket','test-records','Who became the third bowler to take all ten wickets in a men’s Test innings in 2021?','He achieved it for New Zealand against India.','["Ajaz Patel","Patel"]'::jsonb,'Ajaz Patel',0.65,'https://www.icc-cricket.com/news/ajaz-patel-joins-elite-10-wicket-club','ICC record report'),
('cricket','odi-history','Which nation won the first men’s One Day International in 1971?','The match was played at Melbourne.','["Australia"]'::jsonb,'Australia',0.9,'https://www.icc-cricket.com/about/cricket/history-of-cricket/early-cricket','ICC cricket history'),
('rugby','world-cup','What was the score in the 2023 men’s Rugby World Cup final?','South Africa beat New Zealand by one point.','["12-11","12–11","12 11","12 to 11"]'::jsonb,'12–11',0.12,'https://www.rugbyworldcup.com/2023/match/final','Rugby World Cup 2023 final'),
('rugby','womens-world-cup','Which nation won the 2021 Women’s Rugby World Cup, played in 2022?','The hosts defeated England in the final.','["New Zealand","Black Ferns"]'::jsonb,'New Zealand',0.38,'https://www.rugbyworldcup.com/2021/','Women’s Rugby World Cup 2021'),
('rugby','world-cup','Which nation won the inaugural men’s Rugby World Cup in 1987?','They beat France in the final.','["New Zealand","All Blacks"]'::jsonb,'New Zealand',0.65,'https://www.rugbyworldcup.com/2019/archive/1987/overview','Rugby World Cup 1987 archive'),
('rugby','world-cup','Who kicked five drop goals for South Africa in the 1999 Rugby World Cup quarter-final against England?','A Springbok fly-half.','["Jannie de Beer","De Beer"]'::jsonb,'Jannie de Beer',0.9,'https://www.rugbyworldcup.com/2019/archive/1999/overview','Rugby World Cup 1999 archive'),
('nfl','super-bowl','Which team won Super Bowl LIX in February 2025?','They defeated Kansas City in New Orleans.','["Philadelphia Eagles","Eagles","Philadelphia"]'::jsonb,'Philadelphia Eagles',0.12,'https://www.nfl.com/super-bowl/history','NFL Super Bowl history'),
('nfl','draft','Who was selected first overall in the 2018 NFL Draft?','The Cleveland Browns selected this quarterback.','["Baker Mayfield","Mayfield"]'::jsonb,'Baker Mayfield',0.38,'https://www.nfl.com/draft/history/fulldraft','NFL Draft history'),
('nfl','perfect-season','Which team completed the NFL’s only perfect season of the Super Bowl era in 1972?','They finished 17–0 including the postseason.','["Miami Dolphins","Dolphins","Miami"]'::jsonb,'Miami Dolphins',0.65,'https://www.profootballhof.com/football-history/1972-miami-dolphins/','Pro Football Hall of Fame'),
('nfl','super-bowl-mvp','Who was MVP of Super Bowl VII?','A Miami Dolphins safety won the award.','["Jake Scott","Scott"]'::jsonb,'Jake Scott',0.9,'https://www.nfl.com/super-bowl/history','NFL Super Bowl history'),
('nba','champions','Which team won the 2022 NBA championship?','They defeated Boston in six games.','["Golden State Warriors","Warriors","Golden State"]'::jsonb,'Golden State Warriors',0.12,'https://www.nba.com/news/history-nba-champions','NBA champions history'),
('nba','finals-mvp','Who was NBA Finals MVP in 2016?','He led Cleveland back from a 3–1 deficit.','["LeBron James","Lebron James","LeBron","Lebron"]'::jsonb,'LeBron James',0.38,'https://www.nba.com/news/history-finals-mvp-winners','NBA Finals MVP history'),
('nba','mvp','Who won both NBA MVP and Defensive Player of the Year in the 1993–94 season?','He played centre for Houston.','["Hakeem Olajuwon","Olajuwon"]'::jsonb,'Hakeem Olajuwon',0.65,'https://www.nba.com/news/history-mvp-award-winners','NBA MVP history'),
('nba','records','Who became the first unanimous NBA MVP in 2016?','A Golden State guard.','["Stephen Curry","Steph Curry","Curry"]'::jsonb,'Stephen Curry',0.9,'https://www.nba.com/news/history-mvp-award-winners','NBA MVP history'),
('mlb','world-series','Which team won the 2024 World Series?','They defeated the New York Yankees.','["Los Angeles Dodgers","LA Dodgers","Dodgers"]'::jsonb,'Los Angeles Dodgers',0.12,'https://www.mlb.com/postseason/history/world-series','MLB World Series history'),
('mlb','world-series','Which team ended a 108-year championship drought by winning the 2016 World Series?','They defeated Cleveland in seven games.','["Chicago Cubs","Cubs","Chicago"]'::jsonb,'Chicago Cubs',0.38,'https://www.mlb.com/postseason/history/world-series','MLB World Series history'),
('mlb','world-series','Who hit a pinch-hit walk-off home run in Game 1 of the 1988 World Series?','The injured Dodgers outfielder faced Dennis Eckersley.','["Kirk Gibson","Gibson"]'::jsonb,'Kirk Gibson',0.65,'https://www.mlb.com/postseason/history/world-series','MLB World Series history'),
('mlb','awards','Who won the first Cy Young Award in 1956?','A Brooklyn Dodgers pitcher.','["Don Newcombe","Newcombe"]'::jsonb,'Don Newcombe',0.9,'https://www.mlb.com/awards/cy-young','MLB Cy Young Award history'),
('nhl','stanley-cup','Which team won the 2022 Stanley Cup?','They defeated Tampa Bay in six games.','["Colorado Avalanche","Avalanche","Colorado"]'::jsonb,'Colorado Avalanche',0.12,'https://www.nhl.com/news/stanley-cup-champions-winners-complete-list','NHL Stanley Cup champions'),
('nhl','stanley-cup','Which team won its first Stanley Cup in 2018?','They defeated Vegas in five games.','["Washington Capitals","Capitals","Washington"]'::jsonb,'Washington Capitals',0.38,'https://www.nhl.com/news/stanley-cup-champions-winners-complete-list','NHL Stanley Cup champions'),
('nhl','awards','Who won the Hart Memorial Trophy in 1990?','The Edmonton Oilers captain won his first Hart Trophy.','["Mark Messier","Messier"]'::jsonb,'Mark Messier',0.65,'https://www.nhl.com/news/hart-memorial-trophy-winners-complete-list','NHL Hart Trophy winners'),
('nhl','conn-smythe','Who won the Conn Smythe Trophy in both 1974 and 1975?','A Philadelphia Flyers goaltender.','["Bernie Parent","Parent"]'::jsonb,'Bernie Parent',0.9,'https://www.nhl.com/news/conn-smythe-trophy-winners-complete-list','NHL Conn Smythe winners'),
('golf','the-open','Who won The Open Championship in 2023?','The American finished six shots clear at Royal Liverpool.','["Brian Harman","Harman"]'::jsonb,'Brian Harman',0.12,'https://www.theopen.com/previous-opens','The Open previous championships'),
('golf','ryder-cup','Which team won the 2016 Ryder Cup at Hazeltine?','They regained the trophy with a 17–11 victory.','["United States","USA","Team USA","US"]'::jsonb,'United States',0.38,'https://www.rydercup.com/history','Ryder Cup history'),
('golf','the-open','Who became the first British winner of The Open since 1969 when he won in 1985?','A Scotsman won at Royal St George’s.','["Sandy Lyle","Lyle"]'::jsonb,'Sandy Lyle',0.65,'https://www.theopen.com/previous-opens','The Open previous championships'),
('golf','the-open','Who won The Open Championship at Royal Lytham & St Annes in 1969?','He became the first British winner for eighteen years.','["Tony Jacklin","Jacklin"]'::jsonb,'Tony Jacklin',0.9,'https://www.theopen.com/previous-opens','The Open previous championships'),
('tennis','french-open','Who won the 2024 French Open men’s singles title?','He defeated Alexander Zverev in five sets.','["Carlos Alcaraz","Alcaraz"]'::jsonb,'Carlos Alcaraz',0.12,'https://www.rolandgarros.com/en-us/palmares','Roland-Garros roll of honour'),
('tennis','us-open-men','Who won the 2020 US Open men’s singles title?','He came back from two sets down in the final.','["Dominic Thiem","Thiem"]'::jsonb,'Dominic Thiem',0.38,'https://www.usopen.org/en_US/visit/history/mschamps.html','US Open men’s champions'),
('tennis','wimbledon','Who won the 1991 Wimbledon men’s singles title?','He defeated Boris Becker in the final.','["Michael Stich","Stich"]'::jsonb,'Michael Stich',0.65,'https://www.wimbledon.com/en_GB/roll_of_honour/gentlemenssingles.html','Wimbledon gentlemen’s singles roll of honour'),
('tennis','wimbledon','Who won the Wimbledon women’s singles title in 1977, the centenary year?','She remains the most recent British women’s singles champion there.','["Virginia Wade","Wade"]'::jsonb,'Virginia Wade',0.9,'https://www.wimbledon.com/en_GB/roll_of_honour/ladiessingles.html','Wimbledon ladies’ singles roll of honour'),
('horse-racing','major-races','Which horse won the 2024 Grand National?','Paul Townend rode the winner.','["I Am Maximus"]'::jsonb,'I Am Maximus',0.12,'https://www.thejockeyclub.co.uk/aintree/events-tickets/grand-national/about-the-event/history/','The Jockey Club Grand National history'),
('horse-racing','major-races','Which horse won the 2022 Melbourne Cup?','Mark Zahra rode the winner.','["Gold Trip"]'::jsonb,'Gold Trip',0.38,'https://www.vrc.com.au/melbourne-cup-carnival/history/','Victoria Racing Club Melbourne Cup history'),
('horse-racing','triple-crown','Which horse won the US Triple Crown in 2015?','He ended a 37-year wait for a Triple Crown winner.','["American Pharoah","American Pharaoh"]'::jsonb,'American Pharoah',0.65,'https://www.belmontstakes.com/history/triple-crown-winners/','Belmont Stakes Triple Crown history'),
('horse-racing','major-races','Which horse won the 1938 Grand National?','He was the first American-bred winner of the race.','["Battleship"]'::jsonb,'Battleship',0.9,'https://www.thejockeyclub.co.uk/aintree/events-tickets/grand-national/about-the-event/history/','The Jockey Club Grand National history'),
('nascar','cup-series','Who won the 2024 NASCAR Cup Series championship?','It was his third Cup title.','["Joey Logano","Logano"]'::jsonb,'Joey Logano',0.12,'https://www.nascar.com/gallery/all-time-nascar-cup-series-champions/','NASCAR Cup champions'),
('nascar','cup-series','Who won the 2020 NASCAR Cup Series championship?','He drove the No. 9 Chevrolet.','["Chase Elliott","Elliott"]'::jsonb,'Chase Elliott',0.38,'https://www.nascar.com/gallery/all-time-nascar-cup-series-champions/','NASCAR Cup champions'),
('nascar','daytona-500','Who won the 2001 Daytona 500?','He drove for Dale Earnhardt Inc.','["Michael Waltrip","Waltrip"]'::jsonb,'Michael Waltrip',0.65,'https://www.nascar.com/gallery/daytona-500-champions/','NASCAR Daytona 500 champions'),
('nascar','daytona-500','Who won the 1979 Daytona 500, the first broadcast live flag-to-flag nationally in the US?','He avoided the final-lap crash ahead.','["Richard Petty","Petty"]'::jsonb,'Richard Petty',0.9,'https://www.nascar.com/gallery/daytona-500-champions/','NASCAR Daytona 500 champions'),
('indycar','championship','Who won the 2024 IndyCar Series championship?','The Chip Ganassi driver secured a third title.','["Alex Palou","Palou"]'::jsonb,'Alex Palou',0.12,'https://www.indycar.com/Results','INDYCAR official results'),
('indycar','indy-500','Who won the 2021 Indianapolis 500?','The victory made him a four-time winner.','["Helio Castroneves","Hélio Castroneves","Castroneves"]'::jsonb,'Helio Castroneves',0.38,'https://www.indianapolismotorspeedway.com/events/indy500/history/winners','Indianapolis 500 winners'),
('indycar','indy-500','Who won the 2005 Indianapolis 500?','He also won the IndyCar championship that season.','["Dan Wheldon","Wheldon"]'::jsonb,'Dan Wheldon',0.65,'https://www.indianapolismotorspeedway.com/events/indy500/history/winners','Indianapolis 500 winners'),
('indycar','indy-500','Who won the 1985 Indianapolis 500 after the famous spin-and-win moment?','He passed Mario Andretti after recovering.','["Danny Sullivan","Sullivan"]'::jsonb,'Danny Sullivan',0.9,'https://www.indianapolismotorspeedway.com/events/indy500/history/winners','Indianapolis 500 winners'),
('motogp','world-champions','Who won the 2022 MotoGP World Championship?','He became Ducati’s first riders’ champion since 2007.','["Francesco Bagnaia","Bagnaia","Pecco Bagnaia"]'::jsonb,'Francesco Bagnaia',0.12,'https://www.motogp.com/en/world-champions','MotoGP world champions'),
('motogp','world-champions','Who won the 2016 MotoGP World Championship?','A Spanish Honda rider.','["Marc Marquez","Marc Márquez","Marquez","Márquez"]'::jsonb,'Marc Marquez',0.38,'https://www.motogp.com/en/world-champions','MotoGP world champions'),
('motogp','world-champions','Who won the 1993 500cc world championship?','An American Suzuki rider.','["Kevin Schwantz","Schwantz"]'::jsonb,'Kevin Schwantz',0.65,'https://www.motogp.com/en/world-champions','MotoGP world champions'),
('motogp','world-champions','Who won the 1964 500cc world championship?','The British MV Agusta rider also won the 350cc title.','["Mike Hailwood","Hailwood"]'::jsonb,'Mike Hailwood',0.9,'https://www.motogp.com/en/world-champions','MotoGP world champions'),
('superbikes','world-champions','Who won the 2021 World Superbike Championship?','He ended Jonathan Rea’s six-year title streak.','["Toprak Razgatlioglu","Toprak Razgatlıoğlu","Toprak"]'::jsonb,'Toprak Razgatlioglu',0.12,'https://www.worldsbk.com/en/results%20statistics','WorldSBK results and statistics'),
('superbikes','world-champions','Who won the 2013 World Superbike Championship?','A British Kawasaki rider.','["Tom Sykes","Sykes"]'::jsonb,'Tom Sykes',0.38,'https://www.worldsbk.com/en/results%20statistics','WorldSBK results and statistics'),
('superbikes','world-champions','Who won the 2004 World Superbike Championship?','A British Ducati rider.','["James Toseland","Toseland"]'::jsonb,'James Toseland',0.65,'https://www.worldsbk.com/en/results%20statistics','WorldSBK results and statistics'),
('superbikes','world-champions','Who won the 1993 World Superbike Championship?','An American Kawasaki rider.','["Scott Russell","Russell"]'::jsonb,'Scott Russell',0.9,'https://www.worldsbk.com/en/results%20statistics','WorldSBK results and statistics'),
('boxing-pro','heavyweight','Who defeated Wladimir Klitschko to become unified heavyweight champion in 2015?','The British challenger won in Düsseldorf.','["Tyson Fury","Fury"]'::jsonb,'Tyson Fury',0.12,'https://www.wboboxing.com/boxing-history/','WBO boxing history'),
('boxing-pro','heavyweight','Who knocked out Lennox Lewis in 2001 before losing the rematch?','The upset took place in South Africa.','["Hasim Rahman","Rahman"]'::jsonb,'Hasim Rahman',0.38,'https://www.wboboxing.com/boxing-history/','WBO boxing history'),
('boxing-pro','heavyweight','Who did Mike Tyson defeat in 91 seconds in 1988 to become lineal heavyweight champion?','The opponent was unbeaten entering the fight.','["Michael Spinks","Spinks"]'::jsonb,'Michael Spinks',0.65,'https://www.ibhof.com/pages/about/inductees/modern/spinks_michael.html','International Boxing Hall of Fame'),
('boxing-pro','heavyweight','Who did Rocky Marciano knock out to win the heavyweight title in 1952?','The champion was ahead on the scorecards.','["Jersey Joe Walcott","Joe Walcott","Walcott"]'::jsonb,'Jersey Joe Walcott',0.9,'https://www.ibhof.com/pages/about/inductees/modern/marciano.html','International Boxing Hall of Fame'),
('ufc','lightweight','Who defeated Conor McGregor at UFC 229?','He won by fourth-round submission.','["Khabib Nurmagomedov","Khabib","Nurmagomedov"]'::jsonb,'Khabib Nurmagomedov',0.12,'https://www.ufc.com/event/ufc-229','UFC 229 results'),
('ufc','champions','Who defeated Miesha Tate to win the UFC women’s bantamweight title in 2016?','The Brazilian won by first-round submission.','["Amanda Nunes","Nunes"]'::jsonb,'Amanda Nunes',0.38,'https://www.ufc.com/athlete/amanda-nunes','UFC athlete record'),
('ufc','ultimate-fighter','Who won the light-heavyweight final at The Ultimate Fighter 1 Finale?','His bout with Stephan Bonnar became historic.','["Forrest Griffin","Griffin"]'::jsonb,'Forrest Griffin',0.65,'https://www.ufc.com/history','UFC history'),
('ufc','champions','Who became the inaugural UFC heavyweight champion in 1997?','He won the UFC 14 heavyweight tournament.','["Mark Coleman","Coleman"]'::jsonb,'Mark Coleman',0.9,'https://www.ufc.com/history','UFC history')
),
validated as (
  select seed.*
  from seed
  where jsonb_typeof(seed.accepted) = 'array'
    and jsonb_array_length(seed.accepted) > 0
    and length(trim(seed.prompt)) >= 12
    and length(trim(seed.clue)) >= 5
    and length(trim(seed.display)) > 0
    and seed.percentile between 0 and 1
    and seed.source_url like 'https://%'
    and length(trim(seed.source_title)) > 0
    and not exists (
      select 1 from jsonb_array_elements_text(seed.accepted) answer
      where length(trim(answer)) = 0
    )
)
insert into public.question_bank(sport_id,category_key,question_type,format_key,prompt_i18n,clue_i18n,answer_rule,answer_display_i18n,difficulty_b,difficulty_percentile,editorial_difficulty_percentile,difficulty_confidence,quality_score,ambiguity_score,verification_status,source_id,source_url,source_title,content_hash,reviewed_at,active)
select s.id,validated.category_key,'typed_single','classic_trivia',jsonb_build_object('en',validated.prompt),jsonb_build_object('en',validated.clue),jsonb_build_object('accepted',validated.accepted),jsonb_build_object('en',validated.display),case when validated.percentile<.25 then -1.3 when validated.percentile<.5 then -.3 when validated.percentile<.75 then .7 else 1.5 end,validated.percentile,validated.percentile,0,1,0,'verified',editorial.id,validated.source_url,validated.source_title,encode(extensions.digest(validated.prompt,'sha256'),'hex'),now(),true
from validated join public.sports s on s.slug=validated.sport_slug cross join editorial on conflict do nothing;

select public.prepare_verified_question_batch('Verified expansion 10 — wider competitions and historic moments',64);
